language: python

python:
  - "3.4"
  - "3.5"

install:
  - "pip install --upgrade pip"
  - "pip install .[test]"

script: python -m pytest

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
