############################
# Representative values in the QA band.
# If QA_BITPACKED is true, then the values represent the offsets.
# QA_NAN is always a straight value, regardless of QA_BITPACKED.
############################
qa:
  bitpacked: true
  fill: 0
  clear: 1
  water: 2
  shadow: 3
  snow: 4
  cloud: 5
  nan: -1

############################
# Values related to training.
############################
randomforest:
  estimators: 500
  class_min: 600
  class_max: 8000
  target_samples: 20000
  train_exclude:
   - 0
   - 9

############################
# Values related to CCD.
############################
ccd:
  begin_date: 729755
  end_date: 730850
  coef_count: 8  # includes intercept
  bands: # Ensure order by using a dict instead of a simple list.
    0: blue
    1: green
    2: red
    3: nir
    4: swir1
    5: swir2
    6: thermal
