############################
# Representative values in the QA band.
# If QA_BITPACKED is true, then the values represent the offsets.
# QA_NAN is always a straight value, regardless of QA_BITPACKED.
############################
QA_BITPACKED: true
#QA_FILL: 255
#QA_CLEAR: 0
#QA_WATER: 1
#QA_SHADOW: 2
#QA_SNOW: 3
#QA_CLOUD: 4
QA_FILL: 0
QA_CLEAR: 1
QA_WATER: 2
QA_SHADOW: 3
QA_SNOW: 4
QA_CLOUD: 5
QA_NAN: -1

############################
# Values related to training.
############################
RANDOM_FOREST_ESTIMATORS: 100
CLASS_MIN: 600
CLASS_MAX: 8000
TOTAL_SAMPLE_SIZE: 20000

############################
# Reclassify values in the target data set used for training.
############################
TARGET_FROM:
  - 3
  - 4
TARGET_TO:
  - 10
  - 10

test:
  test2:
    - 1
    - 2 
